services:
  - type: worker
    name: manga-update-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
     # You will add this securely via Render dashboard
